version: "3"
services:
  mongo-database:
    image: mongo:4
    container_name: "mongo"
    ports:
      - 27017:27017
  mini-crm-api:
    image: minicrm-api-docker-img
    ports:
      - 8102:8102
    expose:
        - 8080
    links:
      - mongo-database